CANCEL = "Cancel"
COPY_LINK = "Copy Link"
OPEN = "Open"
SHARE = "Share"

LINKED_CONTEXT_MENU_ITEMS = [OPEN, COPY_LINK, SHARE, CANCEL]


ANOTHER_LANGUAGE = "Another language"
COPY = "Copy"
DELETE = "Delete"
EDIT = "Edit"
FORWARD = "Forward"
REPLY = "Reply"
STAR = "Star"
UNSTAR = "Unstar"
TRANSLATE_WITH_GOOGLE = "Translate with Google"
UNTRANSLATE = "Untranslate"
MARKETPLACE = "Marketplace"
TRANSCRIBE_WITH_GOOGLE = "Transcribe with Google"
SAVE_TO_GALLERY = "Save to Gallery"
SAVE_TO_DOWNLOADS = "Save to downloads"

BASE_CONTEXT_MENU_ITEMS = [[STAR], [REPLY], [FORWARD], [DELETE], [TRANSLATE_WITH_GOOGLE], [COPY], [EDIT], [MARKETPLACE]]
CONTACT_CONTEXT_MENU_ITEMS = LOCATION_CONTEXT_MENU_ITEMS = \
    STICKERS_CONTEXT_MENU_ITEMS = [[STAR], [REPLY], [FORWARD], [DELETE]]
VOICE_CONTEXT_MENU_ITEMS = [[STAR], [REPLY], [FORWARD], [DELETE], [TRANSCRIBE_WITH_GOOGLE], []]
MEDIA_CONTEXT_MENU_ITEMS = [[STAR], [REPLY], [FORWARD], [DELETE], [SAVE_TO_GALLERY], [SHARE], []]
FILE_CONTEXT_MENU_ITEMS = [[STAR], [REPLY], [FORWARD], [DELETE], [SAVE_TO_DOWNLOADS], []]
TRANSLATED_CONTEXT_MENU_ITEMS = [[STAR], [COPY], [], [UNTRANSLATE], [ANOTHER_LANGUAGE]]

DELETE_FOR_ALL = "Delete for all"
DELETE_FOR_BOTH = "Delete for both"
DELETE_FOR_ME = "Delete for me"

P2P_DELETE_CONTEXT_MENU_ITEMS = [DELETE_FOR_BOTH, DELETE_FOR_ME, CANCEL]
GROUP_DELETE_CONTEXT_MENU_ITEMS = [DELETE_FOR_ALL, DELETE_FOR_ME, CANCEL]
